---
- name: Ensure HAProxy is installed.
  package: 
    name: haproxy
    state: present

- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'

- name: create haproxy_ssh.systemd service
  template:
    src: haproxy.service.j2
    dest: "/etc/systemd/system/haproxy_ssh{{ctid}}.service"
    mode: 0644
  notify: reload systemctl

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy_ssh.cfg.j2
    dest: "/etc/haproxy/haproxy_ssh.{{ctid}}.cfg"
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: start haproxy

#- shell: systemctl enable aproxy_ssh{{ctid}}.service
#
#- name: Ensure HAProxy is started and enabled on boot.
#  systemd: 
#    name: "haproxy_ssh{{ctid}}"
#    state: started
#    daemon_reload: yes
#    enabled: yes
